'use client';
import { useState } from 'react';
import { useAdminQuery } from '@/components/admin/AdminShell';
import { Panel } from '@/components/admin/charts';
import { PageHead } from '@/components/admin/PageHead';
import type { ExplainResp } from '@/lib/admin/types';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export default function SessionsPage() {
  const [input, setInput] = useState('');
  const [id, setId] = useState<string | null>(null);
  const [q] = useAdminQuery<ExplainResp>(id ? `/v1/admin/sessions/${id}/explain` : null);
  return (
    <>
      <PageHead title="Session explain" lede="Why the guide spoke — or stayed quiet — at each moment of one session. Viewing is audited." />
      <form
        className="inline-form card"
        onSubmit={(e) => {
          e.preventDefault();
          if (UUID.test(input.trim())) setId(input.trim());
        }}
      >
        <label className="field" style={{ flex: 1 }}>
          <span className="label">Session ID</span>
          <input className="input mono" value={input} onChange={(e) => setInput(e.target.value)} placeholder="00000000-0000-0000-0000-000000000000" />
        </label>
        <button type="submit" className="btn btn-primary btn-sm" disabled={!UUID.test(input.trim())}>
          Explain
        </button>
      </form>
      {id ? (
        <div className="grid">
          <Panel title="Stories" state={q} wide>
            {(d) => (
              <div className="table-wrap">
                <table className="dtable">
                  <thead>
                    <tr>
                      <th scope="col">Time</th>
                      <th scope="col">Place</th>
                      <th scope="col">Angle · mode</th>
                      <th scope="col">Generated by</th>
                      <th scope="col">Grounded</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {d.stories.map((s) => (
                      <tr key={s.id}>
                        <td className="mono t-caption">{new Date(s.created_at).toLocaleTimeString()}</td>
                        <td>
                          {s.place_name} <span className="muted t-caption">{s.place_kind}</span>
                        </td>
                        <td>
                          {s.angle} · {s.mode}
                        </td>
                        <td>
                          {s.generated_by}
                          {s.fallback_reason ? <span className="muted t-caption"> ({s.fallback_reason})</span> : null}
                        </td>
                        <td>{s.grounding_ok === null ? '—' : s.grounding_ok ? '✓' : '✗'}</td>
                        <td>{s.status}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </Panel>
          <Panel title="Decision timeline" subtitle="Regime, density, decision, and the top candidates with suppression reasons" state={q} wide>
            {(d) => (
              <ol className="timeline admin-timeline">
                {d.timeline.map((e, i) => (
                  <li key={i}>
                    <span className="mono t-caption muted">{new Date(e.t).toLocaleTimeString()}</span>
                    <span className={`chip ${e.decision === 'start_story' ? 'chip-ok' : e.decision === 'silence' ? '' : 'chip-brand'}`}>{e.decision}</span>
                    <span>
                      {e.target ? <strong>{e.target.name}</strong> : null} {e.reason ? <span className="muted">{e.reason}</span> : null}
                      <span className="t-caption muted-3" style={{ display: 'block' }}>
                        {e.regime} · {e.density}
                        {e.providerCalls !== undefined ? ` · ${e.providerCalls} provider calls` : ''}
                        {e.top.length
                          ? ' · ' +
                            e.top
                              .slice(0, 3)
                              .map((c) => `${c.name} ${c.score.toFixed(2)}${c.eligible ? '' : ` (${c.suppressedBy.join(', ')})`}`)
                              .join('; ')
                          : ''}
                      </span>
                    </span>
                  </li>
                ))}
              </ol>
            )}
          </Panel>
        </div>
      ) : (
        <p className="muted t-body-sm">Enter a session ID from the audit log, a support request, or the WebApp debug drawer.</p>
      )}
    </>
  );
}
