/**
 * Builds the bundled demo data for the native app from the single source of truth in /fixtures.
 * Output: apps/mobile/assets/demo/{places,evidence,traces}.json (git-ignored, regenerated by
 * `start`, `typecheck`, `test`, `export:*` and the EAS `eas-build-post-install` hook).
 *
 * D-005: fixtures are used ONLY for the clearly-labelled offline demo mode and simulation. Set
 * MOBILE_DEMO_FIXTURES=0 to ship empty packs (the app then reports that no scenarios exist).
 * Coordinates are rounded to 6 decimals (~0.1 m) and traces use a compact tuple encoding to keep
 * the JS bundle small.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const mobile = join(here, '..');
const fx = join(mobile, '..', '..', 'fixtures');
const out = join(mobile, 'assets', 'demo');
mkdirSync(out, { recursive: true });

const enabled = process.env.MOBILE_DEMO_FIXTURES !== '0';
const readDir = (d) => readdirSync(join(fx, d)).filter((f) => f.endsWith('.json')).sort();
const r6 = (n) => (typeof n === 'number' ? Math.round(n * 1e6) / 1e6 : n);
const r1 = (n) => (typeof n === 'number' ? Math.round(n * 10) / 10 : n);

const places = enabled ? readDir('places').flatMap((f) => JSON.parse(readFileSync(join(fx, 'places', f), 'utf8'))) : [];
const evidence = enabled ? readDir('evidence').flatMap((f) => JSON.parse(readFileSync(join(fx, 'evidence', f), 'utf8'))) : [];
const traces = {};
if (enabled) {
  for (const f of readDir('traces')) {
    const t = JSON.parse(readFileSync(join(fx, 'traces', f), 'utf8'));
    const t0 = t.fixes[0]?.t ?? 0;
    // Compact tuple form, decoded by src/sim/demo-data.ts: [dtMs, lat, lng, accuracyM, speedMps, headingDeg].
    traces[f.replace(/\.json$/, '')] = {
      name: t.name,
      description: t.description,
      synthetic: t.synthetic,
      hz: t.hz,
      durationS: t.durationS,
      t0,
      route: t.route ? t.route.map((p) => [r6(p.lat), r6(p.lng)]) : null,
      fixes: t.fixes.map((x) => [x.t - t0, r6(x.lat), r6(x.lng), r1(x.accuracyM ?? null), r1(x.speedMps ?? null), r1(x.headingDeg ?? null)]),
    };
  }
}

const write = (name, v) => {
  const p = join(out, name);
  const s = JSON.stringify(v);
  let prev = null;
  try {
    prev = readFileSync(p, 'utf8');
  } catch {
    /* first run */
  }
  if (prev !== s) writeFileSync(p, s); // keep mtime stable for Metro when unchanged
};
write('places.json', places);
write('evidence.json', evidence);
write('traces.json', traces);
console.log(`[prepare-assets] demo data ${enabled ? `${places.length} places, ${evidence.length} evidence packs, ${Object.keys(traces).length} traces` : 'disabled (MOBILE_DEMO_FIXTURES=0)'}`);
